# Generated by Django 5.1.4 on 2025-01-16 16:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0002_payment_delete_category_remove_order_drinks_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='order',
            name='motocycle_type',
            field=models.CharField(choices=[('toyota Camry', 'Toyota Camry'), ('cruiser', 'Cruiser'), ('BMW 3', 'BMW 3'), ('Nissan Qashqai', 'Nissan Qashqai'), ('Mazda CX-5', 'Mazda CX-5'), ('Ford Mustang Convertible', 'Ford Mustang Convertible'), ('dirtbike', 'Dirtbike')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
