# Generated by Django 5.1.4 on 2025-01-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0002_order_created_on_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotorcycleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('engine_capacity', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('max_speed', models.IntegerField(blank=True, null=True)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
