# Generated by Django 5.1.4 on 2025-01-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0003_motorcycletype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='age',
        ),
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='defaultpassword', max_length=50),
        ),
    ]
