# Generated by Django 5.1.4 on 2025-01-26 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0004_remove_customer_age_customer_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='motorcycle_type',
        ),
    ]
