# Generated by Django 5.1.4 on 2025-01-27 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0005_remove_order_created_on_remove_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='cusromer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drinkapp.customer'),
            preserve_default=False,
        ),
    ]
