# Generated by Django 5.1.4 on 2025-01-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinkapp', '0006_payment_cusromer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='cusromer_id',
            new_name='customer_id',
        ),
    ]
